Repository antonymofyou/HireEmployeesVue, pull requests merged in 2024-06, with the labels that each got.

#21 CandidatesList
  src/js/RootClasses.js
  src/pages/candidates/CandidatesList.vue
  src/pages/candidates/CandidatesList/CandidatesListPage.vue
  src/pages/candidates/CandidatesList/components/CandidateCard.vue
  src/pages/vacancy/VacanciesList/VacanciesListPage.vue
  src/pages/vacancy/VacanciesList/components/VacancyCard.vue
  src/router/index.js
Labels: enhancement

#33 Добавлен vite-svg-loader
  package-lock.json
  package.json
  vite.config.js
Labels: enhancement

#38 logoutRedirect
  src/js/RootClasses.js
Labels: fix

#36 VacanciesListFix
  src/pages/vacancy/VacanciesList/VacanciesListPage.vue
  src/pages/vacancy/VacanciesList/assets/icons/plus-icon.svg
  src/pages/vacancy/VacanciesList/components/VacancyCard.vue
Labels: fix

#40 backButtons
  src/assets/icons/back.svg
  src/assets/icons/plus.svg
  src/pages/candidates/CandidatesList/CandidatesListPage.vue
  src/pages/vacancy/EditPage/VacancyEditPage.vue
  src/pages/vacancy/VacanciesList/VacanciesListPage.vue
  vite.config.js
Labels: enhancement

#28 Candidate comments
  src/assets/icons/arrow-down.svg
  src/assets/icons/close.svg
  src/assets/icons/edit.svg
  src/assets/icons/save-black.svg
  src/pages/candidates/CandidatComments.vue
  src/pages/candidates/CandidateComments/CandidateComments.vue
  src/pages/candidates/CandidateComments/components/CommentAddition.vue
  src/pages/candidates/CandidateComments/components/CommentCard.vue
  src/pages/candidates/CandidateComments/components/CommentsBlock.vue
  src/pages/candidates/CandidateComments/components/CommentsQuestions.vue
  src/pages/candidates/CandidateComments/js/CommentsClasses.js
  src/pages/candidates/CandidatesList/CandidatesListPage.vue
  src/pages/candidates/CandidatesList/components/CandidateCard.vue
  src/router/index.js
Labels: enhancement

#42 fix: CandidateComments
  src/App.vue
  src/components/TopSquareButton.vue
  src/pages/candidates/CandidateComments/CandidateComments.vue
  src/pages/candidates/CandidateComments/components/CommentCard.vue
  src/pages/candidates/CandidateComments/components/CommentsBlock.vue
  src/pages/candidates/CandidateComments/components/CommentsQuestions.vue
  src/pages/candidates/CandidateComments/components/CommentsVacancy.vue
  src/pages/candidates/CandidatesList/CandidatesListPage.vue
  src/pages/candidates/CandidatesList/components/CandidateCard.vue
  src/pages/vacancy/EditPage/VacancyEditPage.vue
  src/pages/vacancy/VacanciesList/VacanciesListPage.vue
  src/pages/vacancy/VacancyIdPage/VacancyIdPage.vue
Labels: enhancement

#46 feat/fix: CandidateComments
  package-lock.json
  src/App.vue
  src/components/ButtonIcon.vue
  src/pages/authorization/ManagerAuth.vue
  src/pages/candidates/CandidateComments/CandidateCommentsPage.vue
  src/pages/candidates/CandidateComments/components/CommentAddition.vue
  src/pages/candidates/CandidateComments/components/CommentCard.vue
  src/pages/candidates/CandidateComments/components/CommentsBlock.vue
  src/pages/candidates/CandidateComments/components/CommentsQuestions.vue
  src/pages/candidates/CandidateComments/components/CommentsStatus.vue
  src/pages/candidates/CandidateComments/components/CommentsVacancy.vue
  src/pages/candidates/CandidateComments/js/CommentsClasses.js
  src/router/index.js
Labels: enhancement, fix

#50 CandidateCommentsFix
  src/assets/icons/arrow.svg
  src/pages/candidates/CandidateComments/components/CommentAddition.vue
  src/pages/candidates/CandidateComments/components/CommentCard.vue
  src/pages/candidates/CandidateComments/components/CommentsBlock.vue
  src/pages/candidates/CandidateComments/components/CommentsQuestions.vue
  src/pages/candidates/CandidateComments/components/CommentsStatus.vue
  src/pages/candidates/CandidateComments/components/CommentsVacancy.vue
  src/pages/vacancy/VacanciesList/components/VacancyCard.vue
Labels: fix
